server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: JN
      # namespace: 00a91270-84f1-4f3f-9903-c4311dd8d3a9 #命名空间在dev中
    gateway:
      routes:
        - id: provider-WZY # 路由标示，必须唯一
          uri: lb://providerWZY # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/provider/** # 路径断言，判断路径是否是以/provider开头，如果是则符合
#          filters:
#            - AddRequestHeader=Truth,WZY
        - id: consumer-WZY
          uri: lb://consumerWZY
          predicates:
            - Path=/clients/**
      default-filters:
        - AddRequestHeader=Truth,WZYY