server:
  port: 9003
#  address: 127.0.0.1
spring:
  application:
    name: providerWZY
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: JN #集群名称
        # namespace: 00a91270-84f1-4f3f-9903-c4311dd8d3a9 #命名空间
