server:
  port: 9002
#  address: 127.0.0.1
spring:
  application:
    name: consumerWZY
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.137:8848
        cluster-name: JN
        # namespace: 00a91270-84f1-4f3f-9903-c4311dd8d3a9 #命名空间在dev中
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: 9c5f4e9ea499b75eca75
#            client-secret: afa7ff3468bd6021fc95449c07ea8edca123ffef
#            redirect-uri: http://localhost:9002/login/oauth2/code/github
#            scope: user
#            authorization-grant-type: demo

feign:
  httpclient:
    enabled: true #支持Http开关
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #单个路径的最大连接数
  sentinel:
    enabled: true
                         